### ISSUE TITLE
terminal is closed after command has finished

### ISSUE THREAD

**Issue by heldderarbeit** [flathub/com.geekbench.Geekbench6#5]
I'm running the app by clicking on the icon in the app overview, not by running it from the console. After i click the icon, a terminal opens, the program runs but the terminal window closes itself automatically after the script is done. Is there a possibility of keeping the terminal window 'alive' so I can read the results after the program is done? Maybe something like this: https://askubuntu.com/a/20353

It is also mentioned several times in reviews on the Gnome software store, contributing to the negative overall rating.

![Screenshot From 2024-11-07 22-59-04](https://github.com/user-attachments/assets/1f2ff7fe-6bc5-4e52-82a6-df77ad4a9d78)

**Comment by razzeee** [comment]
That's something your distro/console needs to support, on gnome it keeps open at the end.

![image](https://github.com/user-attachments/assets/8dd84a85-43eb-4b98-980b-85918cba1aa5)

**Comment by heldderarbeit** [comment]
Interesting, I had no idea this is console-specific. it just closes itself automatically on Ptyxis 47.4. If there's nothing to do on your side, I'm fine with this issue being closed.

**Comment by razzeee** [comment]
Should be raised with them then https://gitlab.gnome.org/chergert/ptyxis/-/issues
